# Generated by Django 4.1.7 on 2023-08-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('topic', models.CharField(max_length=150)),
                ('no_of_questions', models.IntegerField()),
                ('time', models.IntegerField(help_text='duration of quiz in minutes')),
                ('required_score_to_pass', models.IntegerField(help_text='required score to pass in %')),
                ('difficulty', models.CharField(max_length=6)),
            ],
        ),
    ]
