# Generated by Django 4.1.7 on 2023-08-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'quizes'},
        ),
    ]
