# Generated by Django 4.1.7 on 2023-09-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_remove_quiz_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='background_color',
            field=models.CharField(default='blue', help_text='enter background color', max_length=50),
        ),
    ]
